FROM ubuntu:latest

RUN apt-get update -y && \
    apt install wget curl build-essential ruby-dev ruby -y && \
    cd /usr/local/src && \
    wget https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.tgz && \
    tar -xvf consul-template_0.19.5_linux_amd64.tgz -C /usr/local/bin && \
    rm consul-template_0.19.5_linux_amd64.tgz

RUN cd /usr/local/src && \
    wget https://releases.hashicorp.com/vault/0.11.3/vault_0.11.3_linux_amd64.zip && \
    unzip vault_0.11.3_linux_amd64.zip -d /usr/local/bin && \
    rm vault_0.11.3_linux_amd64.zip

RUN cd /usr/local/src && \
    wget https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip && \
    unzip consul_1.3.0_linux_amd64.zip -d /usr/local/bin && \
    rm consul_1.3.0_linux_amd64.zip

RUN gem install bundler consult
